"""Scenario: note analytics separate session_summaries from manual notes.

Mental model coverage must be computed over manual notes only — session_summary
notes are auto-generated by Ollama and never carry a mental_model field.
"""

import datetime

from sqlmodel import Session

from wizard.cli.analytics import query_notes
from wizard.models import Note, NoteType


def test_note_breakdown_separates_session_summaries(db_session: Session):
    now = datetime.datetime.now()
    start = datetime.date.today() - datetime.timedelta(days=1)
    end = datetime.date.today() + datetime.timedelta(days=1)

    for _ in range(3):
        db_session.add(Note(
            note_type=NoteType.SESSION_SUMMARY, content="auto-generated", created_at=now,
        ))

    db_session.add(Note(
        note_type=NoteType.INVESTIGATION,
        content="found root cause",
        mental_model="X causes Y via Z",
        created_at=now,
    ))
    db_session.add(Note(
        note_type=NoteType.DECISION,
        content="decided to use approach A",
        created_at=now,
    ))
    db_session.flush()

    result = query_notes(db_session, start, end)

    assert result["session_summaries"] == 3
    assert result["manual_notes"] == 2
    assert result["total"] == 5
    assert result["mental_models_captured"] == 1
    assert result["mental_model_coverage"] == 0.5  # 1 out of 2 manual notes


def test_note_breakdown_all_session_summaries_gives_zero_coverage(db_session: Session):
    now = datetime.datetime.now()
    start = datetime.date.today() - datetime.timedelta(days=1)
    end = datetime.date.today() + datetime.timedelta(days=1)

    for _ in range(5):
        db_session.add(Note(
            note_type=NoteType.SESSION_SUMMARY, content="auto", created_at=now,
        ))
    db_session.flush()

    result = query_notes(db_session, start, end)

    assert result["session_summaries"] == 5
    assert result["manual_notes"] == 0
    assert result["mental_model_coverage"] == 0.0  # no manual notes — not ZeroDivisionError


def test_note_breakdown_empty_window(db_session: Session):
    start = datetime.date.today() - datetime.timedelta(days=1)
    end = datetime.date.today() + datetime.timedelta(days=1)

    result = query_notes(db_session, start, end)

    assert result["total"] == 0
    assert result["session_summaries"] == 0
    assert result["manual_notes"] == 0
    assert result["mental_model_coverage"] == 0.0
