"""add session lifecycle columns

Revision ID: 3fc6e6059028
Revises: c821b5437485
Create Date: 2026-04-18 12:40:20.477144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3fc6e6059028'
down_revision: Union[str, Sequence[str], None] = 'c821b5437485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wizardsession', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    op.add_column('wizardsession', sa.Column('closed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wizardsession', 'closed_by')
    op.drop_column('wizardsession', 'last_active_at')
    # ### end Alembic commands ###
