"""initial

Revision ID: abaf4086789e
Revises: 
Create Date: 2026-04-10 03:05:48.116994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'abaf4086789e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notion_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sa.Enum('STANDUP', 'PLANNING', 'PRESENTATION', 'RETRO', 'ONE_ON_ONE', 'TRAINING', 'GENERAL', name='meetingcategory'), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_created_at'), 'meeting', ['created_at'], unique=False)
    op.create_index(op.f('ix_meeting_notion_id'), 'meeting', ['notion_id'], unique=False)
    op.create_index(op.f('ix_meeting_source_id'), 'meeting', ['source_id'], unique=True)
    op.create_index(op.f('ix_meeting_source_type'), 'meeting', ['source_type'], unique=False)
    op.create_table('task',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=False),
    sa.Column('category', sa.Enum('ISSUE', 'BUG', 'INVESTIGATION', name='taskcategory'), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'BLOCKED', 'DONE', 'ARCHIVED', name='taskstatus'), nullable=False),
    sa.Column('notion_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_created_at'), 'task', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_notion_id'), 'task', ['notion_id'], unique=False)
    op.create_index(op.f('ix_task_source_id'), 'task', ['source_id'], unique=True)
    op.create_index(op.f('ix_task_source_type'), 'task', ['source_type'], unique=False)
    op.create_table('wizardsession',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wizardsession_created_at'), 'wizardsession', ['created_at'], unique=False)
    op.create_table('meetingtasks',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('meeting_id', 'task_id')
    )
    op.create_table('note',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.Enum('INVESTIGATION', 'DECISION', 'DOCS', 'LEARNINGS', 'SESSION_SUMMARY', name='notetype'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['wizardsession.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_created_at'), 'note', ['created_at'], unique=False)
    op.create_index(op.f('ix_note_note_type'), 'note', ['note_type'], unique=False)
    op.create_index(op.f('ix_note_source_id'), 'note', ['source_id'], unique=False)
    op.create_index(op.f('ix_note_source_type'), 'note', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_source_type'), table_name='note')
    op.drop_index(op.f('ix_note_source_id'), table_name='note')
    op.drop_index(op.f('ix_note_note_type'), table_name='note')
    op.drop_index(op.f('ix_note_created_at'), table_name='note')
    op.drop_table('note')
    op.drop_table('meetingtasks')
    op.drop_index(op.f('ix_wizardsession_created_at'), table_name='wizardsession')
    op.drop_table('wizardsession')
    op.drop_index(op.f('ix_task_source_type'), table_name='task')
    op.drop_index(op.f('ix_task_source_id'), table_name='task')
    op.drop_index(op.f('ix_task_notion_id'), table_name='task')
    op.drop_index(op.f('ix_task_created_at'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_meeting_source_type'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_source_id'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_notion_id'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_created_at'), table_name='meeting')
    op.drop_table('meeting')
    # ### end Alembic commands ###
