"""add transcript_path and agent to wizardsession

Revision ID: adf0790585cc
Revises: 3fc6e6059028
Create Date: 2026-04-18 15:59:16.665116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf0790585cc'
down_revision: Union[str, Sequence[str], None] = '3fc6e6059028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wizardsession', sa.Column('transcript_path', sa.String(), nullable=True))
    op.add_column('wizardsession', sa.Column('agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wizardsession', 'agent')
    op.drop_column('wizardsession', 'transcript_path')
    # ### end Alembic commands ###
