"""strip_external_ids

Revision ID: af6f28588a06
Revises: adf0790585cc
Create Date: 2026-04-18 21:20:12.739455

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'af6f28588a06'
down_revision: Union[str, Sequence[str], None] = 'adf0790585cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_notion_id'), table_name='meeting')
    op.drop_column('meeting', 'notion_id')
    op.drop_index(op.f('ix_note_source_id'), table_name='note')
    op.drop_index(op.f('ix_note_source_type'), table_name='note')
    op.drop_column('note', 'source_id')
    op.drop_column('note', 'source_type')
    op.drop_column('note', 'source_url')
    op.drop_index(op.f('ix_task_notion_id'), table_name='task')
    op.drop_column('task', 'notion_id')
    op.drop_column('wizardsession', 'daily_page_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wizardsession', sa.Column('daily_page_id', sa.VARCHAR(), nullable=True))
    op.add_column('task', sa.Column('notion_id', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_task_notion_id'), 'task', ['notion_id'], unique=False)
    op.add_column('note', sa.Column('source_url', sa.VARCHAR(), nullable=True))
    op.add_column('note', sa.Column('source_type', sa.VARCHAR(), nullable=True))
    op.add_column('note', sa.Column('source_id', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_note_source_type'), 'note', ['source_type'], unique=False)
    op.create_index(op.f('ix_note_source_id'), 'note', ['source_id'], unique=False)
    op.add_column('meeting', sa.Column('notion_id', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_meeting_notion_id'), 'meeting', ['notion_id'], unique=False)
    # ### end Alembic commands ###
