"""add task_state mental_model session_state

Revision ID: c821b5437485
Revises: 15146de1d71a
Create Date: 2026-04-13 16:47:04.859457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c821b5437485'
down_revision: Union[str, Sequence[str], None] = '15146de1d71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_state',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('note_count', sa.Integer(), nullable=False),
    sa.Column('decision_count', sa.Integer(), nullable=False),
    sa.Column('last_note_at', sa.DateTime(), nullable=True),
    sa.Column('last_status_change_at', sa.DateTime(), nullable=True),
    sa.Column('last_touched_at', sa.DateTime(), nullable=False),
    sa.Column('stale_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_state_created_at'), 'task_state', ['created_at'], unique=False)
    op.add_column('note', sa.Column('mental_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('wizardsession', sa.Column('session_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # --- Backfill task_state for existing tasks ---
    import datetime as _dt
    from sqlalchemy import text as _sa_text

    bind = op.get_bind()
    now = _dt.datetime.now()

    tasks = bind.execute(
        _sa_text("SELECT id, source_id, created_at FROM task")
    ).fetchall()

    def _to_dt(value):
        # SQLite returns DATETIME columns as ISO strings via raw text();
        # other dialects return datetime objects. Coerce both to datetime.
        if value is None or isinstance(value, _dt.datetime):
            return value
        return _dt.datetime.fromisoformat(value)

    for t in tasks:
        notes = bind.execute(
            _sa_text(
                "SELECT created_at, note_type FROM note "
                "WHERE task_id = :tid "
                "OR (source_id = :sid AND source_type = 'JIRA' AND :sid IS NOT NULL)"
            ),
            {"tid": t.id, "sid": t.source_id},
        ).fetchall()

        note_count = len(notes)
        decision_count = sum(1 for n in notes if n.note_type == "decision")
        note_dts = [_to_dt(n.created_at) for n in notes]
        last_note_at = max(note_dts) if note_dts else None
        task_created_at = _to_dt(t.created_at)
        last_touched_at = last_note_at if last_note_at is not None else task_created_at
        stale_days = (now - last_touched_at).days

        bind.execute(
            _sa_text(
                "INSERT INTO task_state "
                "(task_id, note_count, decision_count, last_note_at, "
                " last_status_change_at, last_touched_at, stale_days, "
                " created_at, updated_at) "
                "VALUES "
                "(:task_id, :nc, :dc, :lna, NULL, :lt, :sd, :now, :now)"
            ),
            {
                "task_id": t.id,
                "nc": note_count,
                "dc": decision_count,
                "lna": last_note_at,
                "lt": last_touched_at,
                "sd": stale_days,
                "now": now,
            },
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wizardsession', 'session_state')
    op.drop_column('note', 'mental_model')
    op.drop_index(op.f('ix_task_state_created_at'), table_name='task_state')
    op.drop_table('task_state')
    # ### end Alembic commands ###
