"""artifact_identity

Revision ID: f0fb7ac74c46
Revises: a9b8c7d6e5f4
Create Date: 2026-04-24 00:48:28.823559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0fb7ac74c46'
down_revision: Union[str, Sequence[str], None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('artifact_id', sa.String(), nullable=True))
    op.add_column('meeting', sa.Column('persistence', sa.String(), nullable=False, server_default='persistent'))
    op.add_column('meeting', sa.Column('workspace', sa.String(), nullable=True))
    op.create_index(op.f('ix_meeting_artifact_id'), 'meeting', ['artifact_id'], unique=True)
    op.add_column('note', sa.Column('artifact_id', sa.String(), nullable=True))
    op.add_column('note', sa.Column('artifact_type', sa.String(), nullable=True))
    op.add_column('note', sa.Column('synthesis_content_hash', sa.String(), nullable=True))
    op.add_column('note', sa.Column('synthesis_session_id', sa.Integer(), nullable=True))
    op.add_column('note', sa.Column('transcript_offset_start', sa.Integer(), nullable=True))
    op.add_column('note', sa.Column('transcript_offset_end', sa.Integer(), nullable=True))
    op.add_column('note', sa.Column('synthesis_confidence', sa.Float(), nullable=True))
    op.add_column('note', sa.Column('source_note_ids', sa.String(), nullable=True))
    op.add_column('note', sa.Column('supersedes_note_id', sa.Integer(), nullable=True))
    op.add_column('note', sa.Column('status', sa.String(), nullable=False, server_default='active'))
    op.add_column('note', sa.Column('reference_count', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_note_artifact_id'), 'note', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_note_synthesis_content_hash'), 'note', ['synthesis_content_hash'], unique=False)
    op.add_column('task', sa.Column('artifact_id', sa.String(), nullable=True))
    op.add_column('task', sa.Column('persistence', sa.String(), nullable=False, server_default='persistent'))
    op.add_column('task', sa.Column('workspace', sa.String(), nullable=True))
    op.create_index(op.f('ix_task_artifact_id'), 'task', ['artifact_id'], unique=True)
    op.add_column('wizardsession', sa.Column('artifact_id', sa.String(), nullable=True))
    op.add_column('wizardsession', sa.Column('persistence', sa.String(), nullable=False, server_default='ephemeral'))
    op.add_column('wizardsession', sa.Column('workspace', sa.String(), nullable=True))
    op.add_column('wizardsession', sa.Column('synthesis_status', sa.String(), nullable=False, server_default='pending'))
    op.create_index(op.f('ix_wizardsession_artifact_id'), 'wizardsession', ['artifact_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wizardsession_artifact_id'), table_name='wizardsession')
    op.drop_column('wizardsession', 'synthesis_status')
    op.drop_column('wizardsession', 'workspace')
    op.drop_column('wizardsession', 'persistence')
    op.drop_column('wizardsession', 'artifact_id')
    op.drop_index(op.f('ix_task_artifact_id'), table_name='task')
    op.drop_column('task', 'workspace')
    op.drop_column('task', 'persistence')
    op.drop_column('task', 'artifact_id')
    op.drop_index(op.f('ix_note_synthesis_content_hash'), table_name='note')
    op.drop_index(op.f('ix_note_artifact_id'), table_name='note')
    op.drop_column('note', 'reference_count')
    op.drop_column('note', 'status')
    op.drop_column('note', 'supersedes_note_id')
    op.drop_column('note', 'source_note_ids')
    op.drop_column('note', 'synthesis_confidence')
    op.drop_column('note', 'transcript_offset_end')
    op.drop_column('note', 'transcript_offset_start')
    op.drop_column('note', 'synthesis_session_id')
    op.drop_column('note', 'synthesis_content_hash')
    op.drop_column('note', 'artifact_type')
    op.drop_column('note', 'artifact_id')
    op.drop_index(op.f('ix_meeting_artifact_id'), table_name='meeting')
    op.drop_column('meeting', 'workspace')
    op.drop_column('meeting', 'persistence')
    op.drop_column('meeting', 'artifact_id')
    # ### end Alembic commands ###
