"""add toolcall table

Revision ID: 15146de1d71a
Revises: bdb1a20e53d2
Create Date: 2026-04-11 16:42:59.524722

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '15146de1d71a'
down_revision: Union[str, Sequence[str], None] = 'bdb1a20e53d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toolcall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('called_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['wizardsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toolcall_called_at'), 'toolcall', ['called_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toolcall_called_at'), table_name='toolcall')
    op.drop_table('toolcall')
    # ### end Alembic commands ###
