"""add daily_page_id to wizardsession

Revision ID: bdb1a20e53d2
Revises: 1bbc6e61da58
Create Date: 2026-04-11 06:37:30.620141

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bdb1a20e53d2'
down_revision: Union[str, Sequence[str], None] = '1bbc6e61da58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wizardsession', sa.Column('daily_page_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wizardsession', 'daily_page_id')
    # ### end Alembic commands ###
